---
- name: "Prepare the environment and build complyctl RPMs in Fedora"
  hosts: demo_vm
  become: false
  vars:
    repo_org: "sonupreetam"  # Replace with your GitHub username
    repo_name: "complyctl"
    spec_file: "complyctl.spec"
  tasks:
    - name: "Ensure removal of packages from previous installation"
      ansible.builtin.dnf:
        name:
          - complyctl
          - complyctl-openscap-plugin
        state: absent
      become: true

    - name: "Install required packages to build complyctl RPMs"
      ansible.builtin.dnf:
        name:
          - go-rpm-macros
          - golang
          - rpmdevtools
          - rpmlint
        state: present
      become: true

    - name: "Ensure the RPM build tree is created"
      ansible.builtin.command:
        cmd: "rpmdev-setuptree"
      changed_when: false

    - name: "Set development version for feature branch"
      ansible.builtin.set_fact:
        latest_version: "dev-{{ ansible_date_time.epoch }}"

    - name: "Clone or update repository"
      ansible.builtin.git:
        repo: "https://github.com/{{ repo_org }}/{{ repo_name }}.git"
        dest: "{{ repo_name }}"
        version: feat/add-user-workspace  # Change to your branch name if needed (e.g., "feature-branch")
        update: true

    - name: "Create tarball from git HEAD"
      ansible.builtin.shell:
        cmd: "set -o pipefail && git archive --format=tar --prefix={{ repo_name }}-{{ latest_version }}/ HEAD
              | gzip > ~/rpmbuild/SOURCES/v{{ latest_version }}.tar.gz"
        chdir: "{{ repo_name }}"
        executable: /bin/bash
      changed_when: true

    - name: "Copy complyctl SPEC file from cloned repository"
      ansible.builtin.copy:
        src: "{{ repo_name }}/{{ spec_file }}"
        dest: "{{ spec_file }}"
        mode: "0640"
        remote_src: true

    - name: "Ensure complyctl SPEC file uses the latest released version"
      ansible.builtin.lineinfile:
        path: "{{ spec_file }}"
        regexp: "^Version:\\s*.*"
        line: "Version:        {{ latest_version }}"

    - name: "Preamble check for the complyctl SPEC file"
      ansible.builtin.command:
        cmd: "rpmbuild -bp {{ spec_file }}"
      register: result_preamble_check
      changed_when: false

    - name: "Show preamble check warnings and errors"
      ansible.builtin.debug:
        msg: "{{ result_preamble_check.stderr_lines | select('match', '^(warning|error)') | list }}"
      changed_when: true
      when: result_preamble_check.stderr_lines | select('match', '^(warning|error)') | length > 0

    - name: "Unmount tmpfs to avoid space issues during this build"
      ansible.posix.mount:
        path: /tmp
        state: unmounted
      become: true

    - name: "Build complyctl RPMs"
      ansible.builtin.command:
        cmd: "rpmbuild -bb --nodebuginfo {{ spec_file }}"
      register: result_build_all
      changed_when: false

    - name: "Show build process warnings and errors"
      ansible.builtin.debug:
        msg: "{{ result_build_all.stderr_lines | select('match', '^(warning|error)') | list }}"
      changed_when: true
      when: result_build_all.stderr_lines | select('match', '^(warning|error)') | length > 0

    - name: "Extract RPM paths from rpmbuild output"
      ansible.builtin.set_fact:
        built_rpm_files: >-
          {{ result_build_all.stdout_lines
            | select('match', '.*\.rpm')
            | map('regex_replace', '^Wrote: ', '')
            | list }}

    - name: "Install complyctl RPMs built locally"
      ansible.builtin.dnf:
        name: "{{ built_rpm_files }}"
        disable_gpg_check: true
        state: present
      become: true

    - name: "Execute plan command to create Assessment Plan"
      ansible.builtin.command:
        cmd: "complyctl plan cusp_fedora"
      changed_when: false

    - name: "Execute generate command to create policy and remediation"
      ansible.builtin.command:
        cmd: "complyctl generate"
      changed_when: false
...
