frameworkId: cusp_fedora
includeControls:
- controlId: cusp_fedora_4-1
  controlTitle: Account Protection
  includeRules:
  - "accounts_umask_etc_login_defs"
- controlId: cusp_fedora_4-2
  controlTitle: Sudo
  includeRules:
  - "sudo_custom_logfile"
- controlId: cusp_fedora_5-2
  controlTitle: Firewall Configuration
  includeRules:
  - "*"
  excludeRules:
  - "service_firewalld_enabled"
  - "service_nftables_disabled"
